### ISSUE TITLE
로딩 시간이 길고 깨집니다

### ISSUE THREAD

**Issue by sepiroslv2** [sokcuri/TweetDeckPlayer#10]
![xzczxcxzcxczxzczxcxzc](https://cloud.githubusercontent.com/assets/18526983/14598357/bd0f33a4-058c-11e6-82c3-e98bee1f6ffe.png)

이런식으로 뜹니다 (github를 처음 이용해봐서 이렇게 업로드하는 게 맞는지 모르겠습니다...)

남아있는 트윗덱 파일 지웠는데도 저렇네요, 확인해보시고 혹시 해결방법이 있으면 알려주세요 ㅠㅠ

**Comment by sokcuri** [comment]
아까 트위터에서 뵌 분이죠? 남아있는 트윗덱과는 별 관계가 없는 문제입니다. 오늘 XP 지원과 더불어 한번 해결해보도록 하겠습니다.

**Comment by sepiroslv2** [comment]
헉 아뇨 트위터에서 뵌 적은 없습니다 ㅋㅋㅋㅋㅋ 저와 비슷한 증상이 있는 모양이네요 감사합니다..! 힘내세용ㅋㅋㅋ

**Comment by sokcuri** [comment]
아 그런가요 ㅋㅋ 마침 이거랑 동일한 증상있으신 분이 계셨는데

**Comment by sokcuri** [comment]
1.23 버전을 공개했는데, 이 버전에도 문제가 발생하는지 한번 확인 부탁드려요

**Comment by sokcuri** [comment]
해당 문제는 cef 엔진을 single_process로 작동시키면서 일어나는 문제입니다. 다만, 멀티 프로세스로 돌렸을 때 몇가지 문제가 발생하기 때문에 이를 해결하기 위한 구조 개선과 테스트가 필요합니다.

**Comment by sepiroslv2** [comment]
아직도 증상 발생하네요...

**Comment by sepiroslv2** [comment]
필요하신 정보 있으시면 언제든지 알려드리겠습니다..!

**Comment by sokcuri** [comment]
1.24 버전에서 문제을 수정했습니다. 한번 확인 부탁드립니다.

**Comment by sepiroslv2** [comment]
감사합니다! 해결됐습니다
