### ISSUE TITLE
리트윗 취소 기능 제안

### ISSUE THREAD

**Issue by YukihoAA** [sokcuri/TweetDeckPlayer#102]
현재 TweetDeck Player에서는 리트윗 버튼을 통한 빠른 리트윗을 지원하고 있는데,

공앱에서 처럼 이미 리트윗 된 트윗의 리트윗 버튼을 누를 경우 리트윗 취소가 가능하게 된다면 좋을 것 같습니다.

**Comment by astrine** [comment]
지금도 그냥 클릭하면 취소가 되긴 됩니다. 따로 이펙트가 없어서 그렇지..

**Comment by YukihoAA** [comment]
그렇네요 리트윗 취소가 되긴 하는데 그대로 초록색이라 리트윗 취소가 되었는지 알 길이 없을 뿐이네요...
