### ISSUE TITLE
데스크톱 알람이 뜨지 않습니다.

### ISSUE THREAD

**Issue by Mitaka-9** [sokcuri/TweetDeckPlayer#105]
현재 2.22 버전을 사용 중입니다. 이전 버전에는 데스크톱 알람이 잘 작동했었던 것으로 기억하는데 현재 데스크톱 알람이 돌아가지 않습니다. 소리 켬을 설정하면 소리만 나오고 이전의 사각 박스에 나오던 알람은 안 나오네요. 윈도우 버전은 윈도우 10 1607입니다.

**Comment by Hoto-Cocoa** [comment]
저는 소리도 안나오네요 어째 알림이 안오더니..

**Comment by sokcuri** [comment]
최신 버전에서 고쳐졌습니다. 감사합니다.
