### ISSUE TITLE
영상 재생 중 리프레시 오류

### ISSUE THREAD

**Issue by lightseller1** [sokcuri/TweetDeckPlayer#106]
트위터에 업로드 된 영상에 한해서 발생하는 오류입니다.

영상 재생 시작 시점에서 1분이 지나면 영상이 다시 처음으로 돌아가는 현상이 발생합니다.

그리고 이 때 영상이 전체화면으로 재생중이었을 경우 전체화면이 강제로 풀리며 트윗덱 플레이어의 레이아웃이 깨지는 현상이 발생합니다.

ps. 꼭 1분이 지나지 않아도 전체화면이 풀리는 경우가 있네요... gif 녹화하면서 처음 봤습니다.
1분이 지나면 확정적으로 전체화면이 풀리면서 레이아웃이 무너집니다.

사용중인 버전은 v2.22이고 윈도우 10 프로 1607 버전 사용중입니다.

![image](https://cloud.githubusercontent.com/assets/9303414/24302575/767bb4a0-10f6-11e7-983d-1cfd3314fc73.png)

![1](https://cloud.githubusercontent.com/assets/9303414/24303079/057c30d4-10f8-11e7-9ad0-99d7e337a07b.gif)

**Comment by sokcuri** [comment]
최신 버전에 electron 업데이트 이후로는 재현되지 않은것 같은데, 해당 증상이 현재도 발생하는지 확인해주세요.

**Comment by lightseller1** [comment]
사용 버전 2.30 현재 해당 현상 재현되고 있지 않습니다.
