### ISSUE TITLE
트윗 작성 칸 내용이 이상하게 보입니다.

### ISSUE THREAD

**Issue by Hoto-Cocoa** [sokcuri/TweetDeckPlayer#107]
![image](https://cloud.githubusercontent.com/assets/21969938/24418852/538a88ce-1428-11e7-8a0c-004a8b00b989.png)
._.)

**Comment by zn** [comment]
어떤 버전을 사용하고 계신가요? 우선 2.22버전(
https://github.com/sokcuri/TweetDeckPlayer/releases/tag/2.22 )으로 업데이트를
해보세요. 그래도 이상이 있다면 다시 한번 확인해보겠습니다.

2017년 3월 29일 (수) 오전 2:36, Hoto Cocoa (Lee Sung Jae) <
notifications@github.com>님이 작성:

**Comment by Hoto-Cocoa** [comment]
업데이트 받고 Quick Access에 고정된 구버전 쓰고 있었네요 ._.)
