### ISSUE TITLE
DM으로 받은 이미지 저장 시 0바이트로 저장되는 현상

### ISSUE THREAD

**Issue by joshua-qa** [sokcuri/TweetDeckPlayer#108]
[발생 환경]
Mac OS Sierra, Windows 10

[재현 스텝]
1. 트윗덱 플레이어에서 DM 탭 접근
2. DM에 포함된 이미지를 클릭 > 오른쪽 클릭하여 이미지 저장
3. 저장된 이미지가 정상적으로 노출되는지 확인

[오류 내용]
DM으로 받은 이미지 저장 시 0바이트로 저장됩니다.
<img width="725" alt="2017-04-21 7 07 46" src="https://cloud.githubusercontent.com/assets/18359200/25273357/6d64aa94-26c6-11e7-9674-103b34c30497.png">

[기대 결과]
이미지가 올바르게 저장되어야 합니다.

[참고 사항]
1. 웹에서 tweetdeck.twitter.com 접근하여 동일한 스텝으로 시도 결과 정상적으로 저장되는 것을 확인하였습니다.
2. 프로텍트 계정 / 일반 계정에게 받은 DM 모두 동일한 현상을 확인하였습니다.

**Comment by sokcuri** [comment]
해당 증상을 확인했습니다. 버그 제보 감사합니다.

**Comment by joshua-qa** [comment]
현재 최신 상태의 master 브랜치 코드로 구동해서 테스트한 결과, 이상없이 수정되었음을 확인하였습니다.
- 일반 계정이 보낸 dm의 이미지 다운로드 >> Pass
- 프로텍트 계정이 보낸 dm의 이미지 다운로드 >> Pass
추후 2.23 릴리즈 된 이후에 이슈 종료처리 하겠습니다. 감사합니다.

**Comment by sokcuri** [comment]
고마워양!
