### ISSUE TITLE
토스트 팝업 오류로 인해 로그인이 불가능한 버그

### ISSUE THREAD

**Issue by ikasty** [sokcuri/TweetDeckPlayer#125]
최신 버전이 아니라 낮은 버전에서, `toaster.showNotification is not a function` 이라는 오류 메시지와 함께 로그인이 되지 않는 버그가 발생합니다. 아마도 버전 정보를 출력하는 토스트 알림 때문인 듯 합니다만, 어떻게 해도 버그 재현을 할 수가 없네요.

오류 상황에 대한 제 추측은 다음과 같습니다.
1. 로그인하여 사용하던 중에 어떤 원인으로든 로그인이 풀린 경우에
2. 트윗덱 메인 페이지가 아닌 로그인 페이지가 뜬 상황에서
3. 토스트 알림 기능이 없으므로 이를 호출하면 오류가 발생
인 듯 합니다.

오류가 발생한 버전은 2.30 버전입니다. 단순히 `data` 폴더를 초기화하는 방식으로 로그아웃하는 경우에는 재현이 되질 않네요. 정보를 알게 되는 대로 기록해 두도록 하겠습니다.

**Comment by sokcuri** [comment]
안녕하세요. 아시겠지만 해당 내용은 2.32 버전 및 최신버전에서 해결한 현상입니다. 혹시 구버전을 쓰는 이유가 따로 있으신지요?

**Comment by sokcuri** [comment]
안녕하세요. 자세한 리포트 잘 받았습니다. 아시다싶이 해당 내용은 2.32 버전 및 최신버전에서 해결한 현상입니다.

오류가 발생하는 원인은 트윗덱의 함수 변경에 있는데, 트윗덱 플레이어는 트윗덱에서 쓰이는 알림 함수를 끌어다 쓰고 있습니다. 트윗덱에서 쓰이는 `toaster.showNotification` 함수가 `window.toastMessage` 함수로 바뀌었는데, 현재는 존재하지 않는 함수를 호출해 오류가 발생한 것입니다.

혹여나 다른 사항이 발견된다면 이슈를 다시 열어주세요. 감사합니다.

**Comment by ikasty** [comment]
아, 저번에 해결되었다는 이슈가 이 이슈였군요. 이미 해결된 이슈라니 다행입니다 :D

**Comment by sokcuri** [comment]
네넵. 관심가져주셔서 고마워요! XD
