### ISSUE TITLE
윈10에서 리트윗 누른 후 모든 클릭, 답글 등 액션 안 됨

### ISSUE THREAD

**Issue by tanolay** [sokcuri/TweetDeckPlayer#133]
아래 맥이 이야기가 있길래 기다렸는데, 여전히 수정이 안 되어 이슈 올립니다.
윈10에서 리트윗을 한 번이라도 클릭하고 나면, 트윗 클릭해도 자세히 볼 수 없고, 답글 등도 안 되고
N을 눌러 새트윗 작성하는 것도 안 됩니다.
그리고 자주 먹통이 되어 꺼지는 현상이 있습니다.

**Comment by happyhappy-jun** [comment]
저도 그러네요 같은 윈도우10이고 리트윗후 트윗 상세내역 확인 안되고, 다른 유저 프로필>트윗 목록등 이것저것 기능이 많이 멈추네요

**Comment by gaeulbyul** [comment]
안녕하세요, https://repo.yona.io/gaeulbyul/TweetDeckPlayer/posts 여기에서 최신 버전을 내려받아 사용해보시겠어요? 여전히 문제가 발생하면 다시 알려주세요.

**Comment by tanolay** [comment]
해당 링크 버전으로 다운받아 확인해보니 해당 문제는 해결되었습니다.
그럼 앞으로 그쪽에서 다운받으면 되는 건가요?

**Comment by gaeulbyul** [comment]
네, 현재 원 개발자(sokcuri)가 유지보수를 못 하고있어서 여기 저장소는 아마 당분간 업데이트가 없을 것입니다...

2018년 3월 5일 (월) 오후 7:30, tanolay <notifications@github.com>님이 작성:

**Comment by happyhappy-jun** [comment]
코멘트 쓰고 이슈 리스트에서 비공식 패치 링크 확인하고 다운 받아서 했더니 해결 됬습니다 감사합니다 ㅎㅎ
