### ISSUE TITLE
Setting란에 있는 기능이 작동하지 않는 문제

### ISSUE THREAD

**Issue by CODE-LA-LI-LU-LE-LO** [sokcuri/TweetDeckPlayer#134]
180702 21:00
기존에 사용하던 기능이 작동되지 않고 있습니다.
옵션 아이콘에서 우클릭하여 들어가는 Setting에 있는 기능 전부가 현재 적용되지 않는 것 같습니다.

**Comment by gaeulbyul** [comment]
트윗덱 내부구조변경이 요새 잦네요... :cry:
https://repo.yona.io/gaeulbyul/TweetDeckPlayer/posts 에서 최신버전으로 내려받아서 확인해주시겠어요?

**Comment by CODE-LA-LI-LU-LE-LO** [comment]
트윗덱 플레이어 v2.34.1-G8 버전으로 확인해보았습니다.
잘 작동됩니다. 감사합니다. :)
