### ISSUE TITLE
내부 브라우저로 페이지 기능

### ISSUE THREAD

**Issue by cokacou** [sokcuri/TweetDeckPlayer#135]
안녕하세요 최신버젼을 사용하고 있으며 내부 브라우저로 페이지 기능을 사용하고 싶은데 찾지 못하여 문의 드립니다. player Settings에 있는지 외부적요소에 있는지 알고 싶습니다. 트윗덱 내 설정에 있다면 어느 항목에 있을까요ㅜ.ㅜ?

**Comment by gaeulbyul** [comment]
안녕하세요, 해당 기능은 보안상의 문제가 될 수 있어서 의도적으로 뺀 기능입니다.

트윗덱플레이어는 Electron(*)을 기반으로 만들어진 프로그램인데,

1. 일반적인 웹 브라우저보다 악의적인 스크립트 등에 더 쉽게 영향받을 위험이 있고,
2. Chromium 엔진의 업데이트가 늦기에 보안업데이트 적용이 다른 브라우저에 비해 늦게 이루어질 수 있습니다.

따라서, 되도록이면 파이어폭스나 크롬 등 외부 브라우저를 통해 웹 페이지를 여는 것을 권합니다.

(*: 데스크탑 앱을 작성하기 위한 프레임워크의 일종으로 내부적으로 Chromium 엔진을 사용합니다.)

- - -

(참, 현재 유지보수중인 버전은 이쪽입니다: https://github.com/gaeulbyul/TweetDeckPlayer )


2019년 7월 8일 (월) 22:30, cokacou <notifications@github.com>님이 작성:

**Comment by cokacou** [comment]
답변 감사합니다!
