### ISSUE TITLE
장기간 구동 시 화면이 하얗게 되며 프리즈되는 문제

### ISSUE THREAD

**Issue by astrine** [sokcuri/TweetDeckPlayer#18]
장기간(약 3~4일)정도 연속 구동시에 어플리케이션 화면이 하얗게 채워지면서 조작이 먹히지 않습니다.
프로그램을 재기동하면 다시 사용 가능합니다만..

**Comment by sokcuri** [comment]
리포트 감사합니다. 해당 문제는 모종의 이유로 렌더러 프로세스가 죽으면서 하얗게 되는 문제입니다. 원인을 파악하는 중입니다. 당분간은 문제가 발생했을 때 프로그램을 재기동시켜 주세요.

**Comment by sokcuri** [comment]
electron 기반의 트윗덱 플레이어에서는 해당 문제가 발생하지 않습니다. 새로운 형태의 트윗덱 플레이어 릴리즈는 수일 내로 이루어질 것으로 보입니다. 만약 비슷한 문제가 다시 발생한다면 이슈를 다시 오픈해 주세요. 감사합니다.
