### ISSUE TITLE
움짤 링크 클릭시 열리는 공웹 화면에서 Video 로딩 되지 않음

### ISSUE THREAD

**Issue by spr0tsuki** [sokcuri/TweetDeckPlayer#19]
이외에도 팝업으로 열리는 창에서 js 지원이 제대로 안 되는듯....? 꺼놓은건가?

**Comment by sokcuri** [comment]
버그인듯. 확인 완료

**Comment by sokcuri** [comment]
CEF는 Notification이 지원되지 않는데, 트위터에서 Notification 기능 여부를 요청할 때 문제가 생기는 것으로 파악되었습니다. 수정 완료. aaa3577023387df7fb696c1326aae6290f679e63

**Comment by spr0tsuki** [comment]
갓발자님 갓갓갓갓
