### ISSUE TITLE
트레이 아이콘 생성

### ISSUE THREAD

**Issue by sokcuri** [sokcuri/TweetDeckPlayer#2]
기존 트윗덱 데스크톱에는 트레이 아이콘이 있어 몇가지 설정을 할 수 있었음. 이것을 추가

Restore window
Open Setting
About TweetDeck
Exit

**Comment by Dalgona** [comment]
#12, 094bc5351fc255a8fced3f3b58375458b5ec7e6e

**Comment by sokcuri** [comment]
Dalgona의 도움으로 무사히 구현되었습니다
