### ISSUE TITLE
Menu of settings doesn't work

### ISSUE THREAD

**Issue by Irbidan** [sokcuri/TweetDeckPlayer#20]
Changing options in the Settings menu don't save options that you choose. I mean the Settings menu doesn't work nowhere. I tested in Windows 10 64-bit fully updated.

Screenshot:
![captura](https://cloud.githubusercontent.com/assets/541941/16531732/18b0029e-3fce-11e6-9c8c-208a02d898a8.PNG)

**Comment by Dalgona** [comment]
It works fine in my environment. Did you extract the program where the administrator privilege is required? (e.g. C:\Program Files, ...)

**Comment by Dalgona** [comment]
The settings are saved into `appdata.ini`, which is located in the same location of the executables. So if you do not have enough privileges to modify files in that location it may not work properly.

**Comment by sokcuri** [comment]
1) Is Window position (Tweetdeck Player save window information when exit) also doesn't save?
2) embedded to 'appdata.ini' file please.

**Comment by Irbidan** [comment]
Now works. I run the app as Administrator. Thank you

**Comment by sokcuri** [comment]
Thanks for participation this issues. I really happy you solve this issue. :>
