### ISSUE TITLE
신 버전 관련하여 개선사항 건의드립니다.

### ISSUE THREAD

**Issue by joshua-qa** [sokcuri/TweetDeckPlayer#21]
안녕하세요. 항상 트윗덱 플레이어를 잘 사용하고 있습니다.
다름이 아니라, 이번 버전에서 아주 약간 불편한 점이 있어서 개선사항 건의드리려고 합니다.

[사용 환경]
Windows 10 / Tweetdeck Player 1.28a

[재현 스텝]
1. 트윗덱 플레이어 실행
2. 컬럼(타임라인)에서 마우스 휠이나 스크롤바를 사용하여 스크롤을 내림
3. 스크롤이 아래로 내려가 있는 상태에서, 컬럼 상단 영역 (Home이나 Notifications..)의 빈 영역을 클릭하여 가장 최근 트윗으로 스크롤되는지 확인

[현재 현상]
빈 공간에 텍스트가 있는것처럼 마우스 커서가 잡혀서, 클릭을 할 수 없습니다.
(스크린샷 기준으로 빨간색 네모가 클릭 불가, 파란색 네모가 클릭 가능 영역)

![image](https://cloud.githubusercontent.com/assets/18359200/16894399/080661e0-4b90-11e6-96a8-cfa21a6a8933.png)

[기대 결과]
빈 공간 클릭이 정상 동작했으면 합니다.
(크롬에서 tweetdeck 접근했을때는 해당 영역이 잘 클릭되는 것을 확인하였습니다)

그럼 확인 부탁드립니다.
감사합니다 (__)

**Comment by sokcuri** [comment]
안녕하세요. 이전 버전은 문제가 없었는지 확인 가능할까요? 저도 클릭 불가능한 빈 공간을 확인했지만, 말씀하신것보단 넓지 않아서 재현이 쉽지 않은 상황입니다.

**Comment by joshua-qa** [comment]
지금 1.27 버전을 설치해서 눌러보았는데 정상 동작을 확인하였습니다. 1.28에서만 재현되는 이슈 같습니다.

**Comment by sokcuri** [comment]
혹시 폰트나 칼럼 변경 등 다른 설정을 변경해 사용중이신가요?

**Comment by joshua-qa** [comment]
appdata.ini는 DisableLinkPopup=1 하나만 적용해서 사용하고 있는 상태입니다~ 폰트나 칼럼 변경은 없었어요

**Comment by sokcuri** [comment]
예 알겠습니다.  몇가지 짚이는 부분이 있긴 한데, 험난한 버그잡기가 예상되네요 ㅠㅠ

**Comment by sokcuri** [comment]
electron 기반의 트윗덱 플레이어에서 해당 부분의 문제를 수정하였습니다. 릴리즈까지는 수일이 소요될 것으로 예상되며, electron 기반에서도 동일한 문제가 일어나면 이슈 부탁드립니다. 감사합니다.

**Comment by joshua-qa** [comment]
2.0.0 수정 확인하였고 특이사항 없습니다. 감사합니다.

**Comment by sokcuri** [comment]
확인해주셔서 감사합니다.
