### ISSUE TITLE
GM-style insecure JS function support

### ISSUE THREAD

**Issue by perillamint** [sokcuri/TweetDeckPlayer#23]
Some GM script (such as, unlink.is) uses GM_ prefixed *insecure* functions.

By implementing this functions, we can easily integrate GM scripts on TweetDeckPlayer but it may introduces some risks when its access didn't controlled and TweetDeck is failed to defend itself from XSS.

What do you think about it?

**Comment by sokcuri** [comment]
electron 포팅 버전 트윗덱 플레이어에서도 이전 버전처럼 script 삽입을 지원할 예정이지만, XSS 보안 설정을 건드리지 않고 해결하고자 합니다. unlink.is의 경우 내장 함수처럼 구현하는것도 방법일것 같습니다.

**Comment by sokcuri** [comment]
GM 함수를 이용해 구현되었습니다.
