### ISSUE TITLE
트윗 작성 시 <foo 와 같은 문자열이 투명해짐.

### ISSUE THREAD

**Issue by perillamint** [sokcuri/TweetDeckPlayer#24]
<foo 와 같은 문자열을 사용할 경우, 글자가 투명해짐

**Comment by sokcuri** [comment]
확인중입니다.

**Comment by sokcuri** [comment]
d5c79e258fa9d87e55096ab4edfe677fecd3db68 에서 수정되었습니다. 이슈 작성 감사합니다.
