### ISSUE TITLE
[Suggestion] About writing a Tweet

### ISSUE THREAD

**Issue by Irbidan** [sokcuri/TweetDeckPlayer#25]
Disable spell-checking feature. It's not necessary and there aren't options to use it correctly.

![captura](https://cloud.githubusercontent.com/assets/541941/18444458/94b1691c-7919-11e6-99cd-2f99ab04f480.PNG)
.

**Comment by sokcuri** [comment]
We are currently working on electron build, I expect that this issue is resolved. Thanks for issue.

**Comment by sokcuri** [comment]
Hey Irbidan! Today We are updated TweetDeck 2.00 that based on Electron.
