### ISSUE TITLE
Vimium 플러그인

### ISSUE THREAD

**Issue by phillyai** [sokcuri/TweetDeckPlayer#28]
[Vimium](https://s18.postimg.org/5c3h7stdl/079.png) 은 크롬 확장 프로그램인데
이런 확장 프로그램 추가할 수 있었으면요

**Comment by sokcuri** [comment]
흐에에엨ㅋㅋㅋ script 폴더 안에 js 파일을 넣으면 스크립트가 돌아갑니다-

**Comment by phillyai** [comment]
왕
