### ISSUE TITLE
이미지를 저장할 경우 무조건 large 크기로 저장하도록

### ISSUE THREAD

**Issue by sokcuri** [sokcuri/TweetDeckPlayer#3]
현재 이미지 저장시 -small, -large 등을 떼어버리도록 되어 있는데, 여기서 더 나아가 이미지를 저장할 경우 large 크기로 저장되도록 하는 건의가 있었고, 구현할 예정.

**Comment by Dalgona** [comment]
이미지를 저장할 때는 `-orig`를 붙이는게 더 좋을 것 같습니다. 원본 품질의 이미지를 받을 수 있거든요.

**Comment by sokcuri** [comment]
OK

**Comment by sokcuri** [comment]
구현 완료. 1.20a
