### ISSUE TITLE
관심글/RT 상태 표시 변경 옵션 문의

### ISSUE THREAD

**Issue by MagmaChipmunk** [sokcuri/TweetDeckPlayer#32]
![2015-06-25 15 25 48](https://cloud.githubusercontent.com/assets/8914838/18615240/98d440ec-7ddc-11e6-9ea6-676ac879ef58.png)

자신이 트윗을 어떤 상태로 두었는지에 따라, 트윗항목의 왼편을 색으로 표시하는 기능이 있었으면 좋겠습니다.
개인적으로는 이쪽이 RT나 Fav마크가 찍힌 것 보다 명시성이 좋았다고 생각하고 있습니다.
예시는 크롬용 Tweetdeck 확장프로그램인 Tweetdeck Enhancer(현재 ModernDeck)에서 지원하던 모습입니다.

**Comment by sokcuri** [comment]
안녕하세요. 트윗의 상태 (Retweet/Favorite/Ret&Fav)에 따라 트윗의 왼편에 표시가 되는 기능이 맞는지요? 예시를 보여주셔서 많은 도움이 되고 있습니다. 딱 저 정도만 구현하면 되는지, 아니면 다른 명시성이 좋은 방안이 있는지요?

**Comment by MagmaChipmunk** [comment]
네, 그 3가지 상태에 따라 왼편에 표시가 되는 기능이 맞습니다.
딱 저정도만 있어도 매우 많은 도움이 되더라구요. 당장은 저 이상 필요하지 않을 것 같습니다.

**Comment by sokcuri** [comment]
예 감사합니다
