### ISSUE TITLE
칼럼의 가로폭을 px단위로 지정할 수 있는 옵션 문의

### ISSUE THREAD

**Issue by MagmaChipmunk** [sokcuri/TweetDeckPlayer#33]
제목 그대로입니다.
현재 각 칼럼 폭이 350px로 표시되는데, 1080p 해상도를 세로로 피벗해서 쓰면 세번째 칼럼이 약간 잘려 표시되는 문제가 있어서 이 기능이 있었으면 좋겠습니다.

**Comment by Dalgona** [comment]
해당 기능은 빠른 시일 내에 추가될 예정입니다. 조금만 기다려주세요:rocket:

**Comment by sokcuri** [comment]
https://github.com/sokcuri/TweetDeckPlayer/releases/tag/2.01 에서 추가되었습니다.
