### ISSUE TITLE
Ubuntu 16.04 LTS 에서 Setting을 찾을 수 없습니다

### ISSUE THREAD

**Issue by yangbeom** [sokcuri/TweetDeckPlayer#34]
![Settings](https://lh3.googleusercontent.com/slojfpKFpx9l88dGz_b94FAtASz41i9-j8-d1Dq7UzIPWGlBvtM4CvlPUL-upVx2K_4Md8NO5M0lhxNjwkJ798aY68nchu5RX9Iu_vYzmLhGx6HYoGKDR4mWXLmg7kN7_5_Y22gOtvkPCMi4xUoh17kWllYhcKSJfAnNKK6xGqm5GzBHxyKE8JuWdcFbNb2eO7twI8pIZYj7tFtkDRBypS4G3932-mT7tz2JDLwSbfHgUQpMrDu0f7HGejq2Vu86-_vNN3Ca6n78iLJYfq-yXr5AMLQ72ImN437yqiHvoBmxn-lHvAiXU-J-nTvSIDMpgE8XAgv6vIsH2uK2rkrnAfbN9oqSgv7AId3Wulfn7TL21GQEf5SJB2LKeTVWVx32WBsj-R5xplqcc_6BbQ4X9RMGWFPSZvE8j2MJK8KAKM97Oh9URgMFlMtKwTx8cxJu2zVna9-IeJ80PiIfVrI_0Alf1kYiJw-ksk2b8obUjYQSgtlNabM7AeY_2LUBRhQcesKTrPbLbxtJZ8jCw0h7mFNLIAnhuwyjrBvP3RmBxY0P6W14OME991hEMbo78ofOAUSH69ySmCHBUSIJvOw1AqOb_wRIRjNpYNolnWP6wD0qonPXCg=w412-h89-no)

**Comment by yangbeom** [comment]
Settings 우클릭에 있군요 죄송합니다.

**Comment by sokcuri** [comment]
메인 메뉴에 없는 것은 의도하지 않은 상황입니다. 다음 버전에 수정하도록 하겠습니다.

**Comment by Dalgona** [comment]
다음 릴리즈에서 좌측 사이드바의 톱니바퀴 아이콘을 눌러서 트윗덱 플레이어 설정을 열 수 있도록 개선될 예정입니다. 참고 바랍니다. :rocket:

![image](https://cloud.githubusercontent.com/assets/2667858/18694060/ed32ce36-7fe1-11e6-870f-94464790d322.png)

**Comment by sokcuri** [comment]
트윗덱 플레이어 2.2.0 버전에서 톱니바퀴 아이콘을 눌러 트윗덱 플레이어 설정을 열 수 있도록 개선되었습니다. 감사합니다.
