### ISSUE TITLE
글자 입력시 커서의 위치와 글자의 위치가 안맞는 문제

### ISSUE THREAD

**Issue by yangbeom** [sokcuri/TweetDeckPlayer#43]
글을 작성하다 보면  커서의 위치와 글자가 안맞는 상황이 발생합니다.

같은 글에서도 기본 폰트에서는 일어나지 않으나 그 상태에서  다른폰트로 변경하여 보았을때 
글자가 커서를 넘어 가는 것으로 보아 폰트 특성에 따른 현상으로 생각됩니다.

**Comment by sokcuri** [comment]
해당 문제는 하이라이트 기능 구현을 위한 div와 textarea간 글자의 word-wrap이 일치하지 않는 문제이며 수정중입니다. 이슈 감사합니다.

**Comment by sokcuri** [comment]
https://github.com/sokcuri/TweetDeckPlayer/commit/c62285d572a2e8ea2827e7dde46f40a4109a1d43 에서 word-break를 break-all로 바꾸는 방법으로 임시조치했으나 줄바꿈 구현이 필요함.

**Comment by Dalgona** [comment]
하이라이팅 기능은 문제가 많아 최신 버전에서 일시적으로 제거되었습니다.
