### ISSUE TITLE
development branching

### ISSUE THREAD

**Issue by TintypeMolly** [sokcuri/TweetDeckPlayer#45]
On github, the index page of a repository shows the contents on its `master` branch.

So frequent changes on the `master` branch may cause confusion for code readers and contributors.

My suggestion is to create a branch named something like `develop` which developers would apply usual changes to, and to merge it into the `master` branch only when it needs to be tagged and released.

If this strategy is applied, github would always shows buildable project to people at the index page.

**Comment by sokcuri** [comment]
브랜치 정리 이후 1.03부터 develop branch를 사용하도록 하겠습니다.
