### ISSUE TITLE
Twtlib 상용구 삭제 시 가끔씩 Tweekdeck Player가 최소화되는 문제

### ISSUE THREAD

**Issue by kygn1998** [sokcuri/TweetDeckPlayer#49]
Twtlib 상용구를 remove하고 Twtlib을 닫을 때 가끔씩 Tweekdeck Player가 최소화 됩니다.

**Comment by sokcuri** [comment]
사용중인 운영체제를 알려주시면 많은 도움이 됩니다. 닫지 않으면 Tweetdeck Player가 최소화되지 않나요?

**Comment by kygn1998** [comment]
Window 10 x64입니다.
상용구사전을 닫을 때만 최소화되네요

**Comment by sokcuri** [comment]
문제를 확인했습니다. 이슈 감사합니다.
> 해당 문제는 confirm() 함수로 인해 twtlib 윈도우가 focusing을 잃어버리기 때문에 발생
>  twtlibWin.on('close' .. 아래 win.focus() 추가
