### ISSUE TITLE
이미지 뷰어에 대해 건의드립니다.

### ISSUE THREAD

**Issue by joshua-qa** [sokcuri/TweetDeckPlayer#59]
안녕하세요.
트윗덱 플레이어를 사용하면서 들어갔으면 하는 기능이 있었는데, 혹시 이것도 구현이 가능할지에 대해 건의드립니다.
설명을 위해 부득이하게 sokcuri님의 타임라인을 활용한점 양해 부탁드립니다(__)

![image](https://cloud.githubusercontent.com/assets/18359200/19020883/d5fe36c6-88ef-11e6-9ff0-fe337f840a38.png)

[재현 스텝]
1) 타임라인에서 유저네임을 클릭
2) 해당 유저의 타임라인에 직접 들어가기
3) 해당 유저의 타임라인에서 이미지 클릭 후 확인

[현재 상태] 
브라우저를 새로 띄워서 해당 이미지를 보여줍니다.

[개선 사항]
특정 유저의 타임라인에서 이미지 클릭했을 때에도, 전체 타임라인에서 이미지 클릭한것과 동일하게 보여주는 옵션이 있었으면 합니다.
가끔씩 특정 유저의 타임라인을 직접 들어가서 이미지를 눌러볼때가 있는데... 브라우저가 따로 뜨니까 조금 불편할때가 있습니다.
ini 파일에서 옵션 값을 0으로 줬을 때 : 브라우저로 따로 이동해서 보여주기
옵션 값을 1로 줬을 때 : 아래 스크린샷처럼 보여주기
-> 이런식으로 구현되어도 좋을듯 합니다. (가능하다면..)

![image](https://cloud.githubusercontent.com/assets/18359200/19020898/1e2395e0-88f0-11e6-8ce1-7a085ad22530.png)

항상 플레이어 잘 쓰고 있습니다. 감사합니다.

**Comment by sokcuri** [comment]
이미지를 클릭했을때 타임라인에서 이미지를 클릭했을때와 같이 동작하도록 말이죠? 알겠습니다-

**Comment by joshua-qa** [comment]
2.2.0 릴리즈 버전에서 수정되었음을 확인하였습니다.
사이드 이펙트 발견 시, 별도 이슈로 등록하도록 하겠습니다.
감사합니다.

**Comment by sokcuri** [comment]
기여해 주셔서 감사합니다~
