### ISSUE TITLE
트윗 작성시 Enter와 Ctrl+Enter 의 기능을 스위치하는 옵션 추가

### ISSUE THREAD

**Issue by Darkttd** [sokcuri/TweetDeckPlayer#6]
트윗 작성시에 Enter와 Ctrl+Enter 의 기능을 스위치하는 옵션이 있었으면 좋겠습니다.

**Comment by sokcuri** [comment]
Enter와 Ctrl+Enter의 기능을 스위치하는 옵션 또한 스크립트로 구현하는게 맞는것 같습니다.

**Comment by sokcuri** [comment]
현재 electron 기반의 트윗덱 플레이어에서 'Enter key to Tweet' 이라는 옵션으로 구현되었습니다.
