### ISSUE TITLE
다중 계정 사용자를 위한 개선 사항

### ISSUE THREAD

**Issue by joshua-qa** [sokcuri/TweetDeckPlayer#62]
트윗덱의 경우 다중 계정 사용 시, Default Account 변경이 조금 번거로운 편인데요.
몇 가지 방안을 생각해본 결과 toggle에 대한 단축키를 지정할 수 있으면 좋겠다는 생각을 했습니다. (설정 파일 등으로?)
사용자가 별도의 스크립트 작성으로 해결 할 수 있는 사항인 경우, 그쪽으로 한번 해결해볼게요 ^^
해당 개선 사항이 기술적으로 구현 가능한지 잘 모르겠어서 우선 이슈로 남겨봅니다.
![2017-02-06 12 51 15](https://cloud.githubusercontent.com/assets/18359200/22634206/fa1e3a7c-ec6a-11e6-88e6-2d7df1ef437c.png)

**Comment by joshua-qa** [comment]
2.2.0 릴리즈 버전에 해당 스크립트가 반영된 것을 확인하였으나, 변경 사항에 기재되어있는 Ctrl+<0-9> 단축키가 동작하지 않고 있습니다. 개발자 도구를 켜놓고 확인했을 때도 별다른 변화가 감지되진 않았는데요~
재현 환경은 윈도우10 64bit / 트윗덱 플레이어 2.2.0 릴리즈 버전 (x64) 입니다.
번거로우시겠지만 확인 부탁드리겠습니다 (__)

**Comment by sokcuri** [comment]
윈도우 10 64비트에서 테스트를 완료했습니다. v2.21버전에서 정상 작동합니다. 혹시 다른 이슈 있으시면 언제든 열어주세요.

**Comment by joshua-qa** [comment]
2.21 버전에서 수정되었음을 확인하였습니다.
감사합니다.
