### ISSUE TITLE
Minimize Scroll Animation 이 동작하지 않는 문제

### ISSUE THREAD

**Issue by MagmaChipmunk** [sokcuri/TweetDeckPlayer#63]
제목 그대로입니다. 일주일 전 쯤 부터 갑자기 적용되지 않네요.

**Comment by sokcuri** [comment]
안녕하세요. 2.2.0 버전에서 해당 문제가 수정되었습니다. 다른 이슈 있으시면 언제든지 이슈 페이지를 이용해 주세요. 감사합니다.
