### ISSUE TITLE
메모리 비우기 기능

### ISSUE THREAD

**Issue by astrine** [sokcuri/TweetDeckPlayer#68]
트윗덱 플레이어를 오래(약 일주일 이상) 켜두면 트윗이 쌓이면서 플레이어 자체가 굉장히 느려집니다.
지금은 프로그램을 임의로 껐다 키거나 reload 버튼을 눌러서 비워주는데 파라매터 입력으로 자동으로 리로드할 수 있으면 좋지 않을까 싶습니다.
ex. 매 24시간 마다 / 쌓인 트윗이 n개 이상일 때 등

**Comment by sokcuri** [comment]
어떤 방법이 제일 좋을지 고민중인데.. 트윗덱 플레이어 메모리 누수가 왜 나는지를 확인하고 근본적인 처방을 하는 방법도 병행하는게 좋아보이는듯. 임시방편으로 몇시간마다 Reload 해주는게 좋아보일듯 (이건 설정에서 지정할수 있게)
