### ISSUE TITLE
우클릭 context 메뉴 관련

### ISSUE THREAD

**Issue by astrine** [sokcuri/TweetDeckPlayer#69]
이전 버전에서는 외부 브라우저로 열기 / 내부 브라우저로 보기 버튼이 따로 있어서 용도에 따라 분리할 수 있었는데
(ex. 그림쟁이 미디어 페이지를 내부 브라우저로 열어서 짤 저장(우클릭->save image가 편리해서 사용중). 그 외의 용도로 사용하기엔 불편해서 외부 브라우저를 사용)
해당 기능이 사라져서 굉장히 아쉽습니다.

context 메뉴 항목을 on/off로 추가/제거가 가능하면 좋겠습니다.

**Comment by sokcuri** [comment]
다음 버전에 컨텍스트 메뉴를 추가하도록 하겠습니다~

**Comment by sokcuri** [comment]
2.21에서 추가되었습니다.
