### ISSUE TITLE
Setting의 alternative image viewer가 작동하지 않는 문제

### ISSUE THREAD

**Issue by MagmaChipmunk** [sokcuri/TweetDeckPlayer#70]
옵션을 활성화 하고 타임라인의 그림을 클릭하였을 시, 아무런 동작이 이루어지지 않습니다.
비활성화하면 이전처럼 이미지를 확대해서 잘 보여줍니다.
170217 v2.2.0

**Comment by sokcuri** [comment]
현재 올라온 v2.2.0 버전으로 다시 한번 다운받아서 확인해 보시겠어요? 그 문제를 해결한 버전이 올라와 있습니다. 릴리즈 도중 버그를 발견한지라 판올림없이 바로 재업로드했는데 문제가 생긴것 같습니다.

**Comment by sokcuri** [comment]
해당 현상 재현에 성공했습니다.

**Comment by sokcuri** [comment]
2.21 버전에서 해당 문제가 수정되었습니다
