### ISSUE TITLE
alternative image viewer 개선사항

### ISSUE THREAD

**Issue by joshua-qa** [sokcuri/TweetDeckPlayer#71]
[현재현상]
높이가 작은 이미지를 보는 경우 너무 위에서 노출됩니다.

[개선사항]
이미지 높이가 작은 경우 가운데에서 노출되면 좋을 것 같습니다.

검토 부탁드리겠습니다.
감사합니다.
![issue](https://cloud.githubusercontent.com/assets/18359200/23049524/04b2304a-f500-11e6-98aa-88f9268354eb.png)

**Comment by sokcuri** [comment]
2.21 버전에서 뷰어 이미지가 가운데 정렬이 되도록 개선되었습니다.

**Comment by joshua-qa** [comment]
2.21 버전에서 수정되었음을 확인하였습니다.
감사합니다.
