### ISSUE TITLE
Ubuntu 16.04 LTS x64에서 실행이 되지 않습니다.

### ISSUE THREAD

**Issue by yangbeom** [sokcuri/TweetDeckPlayer#75]
`chmod +x TweetDeckPlayer` 이후 실행이 잘 되는 것으로 보아 실행 권한이 없어서 나타나는 현상으로 보입니다.

**Comment by sokcuri** [comment]
압축을 풀면 보통 폴더의 퍼미션을 따라가지 않나요?

**Comment by yangbeom** [comment]
압축을 푼 폴더의 퍼미션은 `775` 였으며 `unzip` 명령어로 압축을 푼후 실행 파일의 퍼미션은 `664` 였습니다.

![Imgur](http://i.imgur.com/S7nyopp.png)

**Comment by sokcuri** [comment]
수정하도록 하겠습니다. 제보 감사합니다.

**Comment by sokcuri** [comment]
퍼미션 문제를 수정한 압축파일을 재업로드했습니다. 감사합니다.
