### ISSUE TITLE
이미지 뷰어

### ISSUE THREAD

**Issue by YukihoAA** [sokcuri/TweetDeckPlayer#77]
이미지 뷰어에서 사진을 클릭하면 다음 사진으로 넘어가게 하는 기능을 넣었으면 좋겠습니다.

**Comment by Dalgona** [comment]
괜찮은 아이디어인 것 같습니다. 구체적으로 어떤 방식으로 지원되었으면 하나요? 일단 저는 두 가지 아이디어가 떠오르는데요,

1. 이미지를 클릭할때마다 순환 (1 &rarr; 2 &rarr; 3 &rarr; 1 &rarr; &hellip;)
2. 이미지의 좌측 반쪽을 누르면 이전 이미지로, 우측 반쪽을 누르면 다음 이미지로

이외에 다른 의견 있으시면 알려주세요~

**Comment by YukihoAA** [comment]
저는 첫번째와 같은 동작을 생각했는데 두번째도 좋은 것 같네요.

**Comment by sokcuri** [comment]
2.22 버전에서 반영되었습니다.
