### ISSUE TITLE
클립보드로부터 이미지 붙여넣기.

### ISSUE THREAD

**Issue by Darkttd** [sokcuri/TweetDeckPlayer#8]
현재 클립보드로부터 이미지를 가져오려면 먼저 파일로 만든다음 불러와야 하는 불편함이 있습니다. Ctrl+V 등으로 바로 클립보드로부터 이미지를 가져올 수 있으면 좋겠습니다.

**Comment by sokcuri** [comment]
해당 기능은 스크립트로 구현해야 할것 같습니다.

**Comment by sokcuri** [comment]
https://gist.github.com/zn/4f622ba80513e0f4d0dd3f13dcd085db
가을별님이 트윗덱에서 클립보드 이미지를 붙여넣을 수 있는 스크립트를 작성하셨습니다. 복사하고 script 폴더 안에 붙여넣으면 됩니다.

**Comment by Darkttd** [comment]
기본으로 script 폴더 안에 포함되어있지 않고, 수동으로 스크립트를 넣어야만 작동하게 하는 특별한 이유라도 있는지요..?

**Comment by sokcuri** [comment]
가을별님에게 허락을 구하고 버전 업데이트를 통해서 스크립트 폴더 안에 포함시킬 예정입니다 :3
