### ISSUE TITLE
Windows 터치 환경에서 텍스트 선택시 크래시

### ISSUE THREAD

**Issue by Rubik-Orange** [sokcuri/TweetDeckPlayer#84]
TweetDeck Player 2.21
서피스 프로 3 (Windows 10 Pro)

에서 터치 조작으로 트윗 텍스트를 선택시 응답 없음이 되다가 Electron has stopped working 창 뜨며 종료됩니다.

**Comment by sokcuri** [comment]
확인 완료. https://github.com/electron/electron/releases/tag/v1.6.1 Electron 자체 버그로 추정되며 다음 업데이트에 해결하도록 하겠습니다.

**Comment by sokcuri** [comment]
2.22버전에서 Electron을 업데이트하였습니다. 똑같은 문제가 재발생하면 Reopen을 눌러 다시 이슈를 열어주세요!
