### ISSUE TITLE
텍스트 사이즈 조절

### ISSUE THREAD

**Issue by astrine** [sokcuri/TweetDeckPlayer#90]
현재 트윗덱 플레이어를 3개 환경에서 사용중입니다.(데스크탑 * 2, 노트북)

노트북이나 데스크탑1에서는 트윗덱 자체 텍스트 사이즈 옵션으로 크게 문제가 없으나,

데스크탑2에서 트윗덱 플레이어를 구동중인 모니터 해상도가 좀 더 높아서 텍스트 사이즈를 조금 키워서 사용하고 싶습니다.

트윗덱 자체 옵션은 전체 동기화가 되어 버리기 때문에 column size옵션처럼 텍스트 크기도 조절 가능하면 좋을 것 같습니다.

**Comment by sokcuri** [comment]
다음 버전에 텍스트 사이즈 기능을 추가하도록 할게요.
