### ISSUE TITLE
텍스트 우클릭시 복사 기능

### ISSUE THREAD

**Issue by YukihoAA** [sokcuri/TweetDeckPlayer#93]
텍스트에 드래그 한 뒤 우클릭을 했을때 인용 기능은 들어있는데 

가장 기본적인 복사가 우클릭 메뉴에 없네요.. 

텍스트를 드래그 한 경우에 복사를 할 수 있도록 우클릭 메뉴에 항목을 추가하면 좋을 것 같습니다.

드래그 하지 않은 경우에도 복사를 할 수 있도록 하는 것도 좋겠네요.

**Comment by sokcuri** [comment]
진짜 없네요 허 ㅋㅋㅋ..

**Comment by ikasty** [comment]
이 이슈는 해결된 듯 하니 닫아도 되지 않을까요.... 마찬가지로 #90 도 닫아도 괜찮을 것 같네요.
