### ISSUE TITLE
텍스트 입력시 텍스트가 반 줄 정도 아래로 표시됨

### ISSUE THREAD

**Issue by cjeon** [sokcuri/TweetDeckPlayer#95]
![image](https://cloud.githubusercontent.com/assets/19306825/23410821/caf5ee88-fe13-11e6-8468-eb9e284a5db3.png)

텍스트가 원래 있어야 할 위치보다 아래로 표시됩니다. 커서, 텍스트 선택시 나타나는 블락은 제자리에 잘 표시됩니다.

빌드버전은 TweetDeck Player v2.01a by @sokcuri @d57_kr @gaeulbyul (TweetDeck 4.0.170224173027-716b054) 이렇게 되어있네요.

**Comment by Dalgona** [comment]
오래된 버전을 사용하고 계십니다. 최신 버전에서 수정된 문제이므로 [업데이트 해주세요](https://github.com/sokcuri/TweetDeckPlayer/releases)!
