### ISSUE TITLE
트윗 작성창 커서 위치

### ISSUE THREAD

**Issue by noxa11** [sokcuri/TweetDeckPlayer#98]
<img src="http://upload2.inven.co.kr/upload/2017/03/03/bbs/i14148508617.gif">

트윗덱 잘 사용하고 있습니다 감사합니다 'ㅅ')!
최근 업데이후 이후 트윗작성창에서 커서위치가 맞지않습니다. 사용환경은 윈7이에요

**Comment by Dalgona** [comment]
[2.22 버전 이상으로 업데이트 해주세요.](https://github.com/sokcuri/TweetDeckPlayer)
